### ISSUE TITLE
yasnippet breaks with c header file(c-mode)

### ISSUE THREAD

**Issue by netjune** [capitaomorte/yasnippet#666] opened 2016-03-01 23:55 UTC
The problem is with the "once" snippet as the following:
```
# name: #ifndef XXX; #define XXX; #endif
# key: once
# --
#ifndef ${1:_`(upcase (file-name-base buffer-file-name))`_H_}
#define $1
#ifdef __cplusplus
extern "C"{
#endif

$0

#ifdef __cplusplus
}
#endif
#endif /* $1 */
```

After expanding, when I press `<tab>`, cursor doesn't go to the right position($0), but goes to beginning of the current line.
If setting add-log-current-defun-function to nil, there is no problem then.

**Comment by npostavs** [comment] 2016-03-16 03:26
I can't reproduce. Please post exact versions of yasnippet and Emacs being used.

**Comment by netjune** [comment] 2016-03-18 13:45
> 在 2016年3月16日，11:26，Noam Postavsky <notifications@github.com> 写道：
> 
> I can't reproduce. Please post exact versions of yasnippet and Emacs being used.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/capitaomorte/yasnippet/issues/666#issuecomment-197134924>
Emacs: 24.5
yasnippet: 0.8.0

**Comment by npostavs** [comment] 2016-03-19 02:33
> yasnippet: 0.8.0

Ok, that's the old version in GNU ELPA. It may be fixed with the latest version from git (or MELPA). The GNU ELPA should be updated Real Soon Now (see #512).

**Comment by netjune** [comment] 2016-03-19 10:09
> 在 2016年3月19日，10:33，Noam Postavsky <notifications@github.com> 写道：
> 
> yasnippet: 0.8.0
> 
> Ok, that's the old version in GNU ELPA. It may be fixed with the latest version from git (or MELPA). The GNU ELPA should be updated Real Soon Now (see #512 <https://github.com/capitaomorte/yasnippet/issues/512>).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/capitaomorte/yasnippet/issues/666#issuecomment-198619466>
I downloaded it from the master about 3 months ago. It is no too old.

;; Version: 0.8.1
;; Package-version: 0.8.0

**Closed** 2016-04-16 15:31 UTC
Labels: cannot reproduce, need clarification
