### ISSUE TITLE
Invalid character: 8677, #o20745, #x21e5 on Carbon Emacs

### ISSUE THREAD

**Issue by nishio** [capitaomorte/yasnippet#345] opened 2012-12-12 02:56 UTC
I cloned the repository HEAD (4f99f9d) and make .emacs.el with only 2 lines below:

(add-to-list 'load-path "~/.emacs.d/plugins/yasnippet")
(require 'yasnippet)

However it causes error: Invalid character: 8677, #o20745, #x21e5

This is GNU Emacs 22.2.50.1 (i386-apple-darwin9.4.0, Carbon Version 1.6.0)
 of 2008-07-17 on seijiz.local

**Comment by npostavs** [comment] 2016-04-19 16:45
I'm closing, as the problem is only confirmed on Emacs 22. I'm not going to support versions earlier than 23 (though I wouldn't reject patches to make things work on Emacs 22 if someone really wants to support it themselves).

**Closed by npostavs** 2016-04-19 16:45 UTC
Labels: low priority
