### ISSUE TITLE
ELPA yasnippet fails on Emacs-25

### ISSUE THREAD

**Issue by phillord** [capitaomorte/yasnippet#650] opened 2016-01-21 12:16 UTC
The version of yasnippet in ELPA currently fails on the head of
Emacs-25. At this will be moving toward pre-release soon, it
would be nice to have a version on ELPA that works with it!

This is the backtrace from a clean Emacs-25 after calling yas-global-mode.

    Debugger entered--Lisp error: (wrong-type-argument integerp nil)
      yas--populate-template([cl-struct-yas--template nil nil nil nil nil nil nil nil nil nil nil nil] :table [cl-struct-yas--table "emacs-lisp-mode" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil (keymap)] :key "yes-or-no-p" :content "(yes-or-no-p \"PROMPT$0 \")" :name "yes-or-no-p" :group nil :condition nil :expand-env nil :file "/tmp/elpa/yasnippet-0.8.0/snippets/emacs-lisp-mode/yes-or-no-p.yasnippet" :keybinding nil :uuid "yes-or-no-p")
      yas-define-snippets-1(("yes-or-no-p" "(yes-or-no-p \"PROMPT$0 \")" "yes-or-no-p" nil nil nil "/tmp/elpa/yasnippet-0.8.0/snippets/emacs-lisp-mode/yes-or-no-p.yasnippet" nil nil) [cl-struct-yas--table "emacs-lisp-mode" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil (keymap)])
      yas-define-snippets(emacs-lisp-mode (("yes-or-no-p" "(yes-or-no-p \"PROMPT$0 \")" "yes-or-no-p" nil nil nil "/tmp/elpa/yasnippet-0.8.0/snippets/emacs-lisp-mode/yes-or-no-p.yasnippet" nil nil) 
      yas--load-directory-2("/tmp/elpa/yasnippet-0.8.0/snippets/emacs-lisp-mode" emacs-lisp-mode)
      yas--load-directory-1("/tmp/elpa/yasnippet-0.8.0/snippets/emacs-lisp-mode" emacs-lisp-mode (text-mode))
      eval((yas--load-directory-1 "/tmp/elpa/yasnippet-0.8.0/snippets/emacs-lisp-mode" (quote emacs-lisp-mode) (quote (text-mode))))
      yas--load-pending-jits()
      yas-minor-mode(1)
      yas-minor-mode-on()

**Comment by npostavs** [comment] 2016-01-21 16:53
> The version of yasnippet in ELPA currently fails

Yeah, that is way out of date. I still have to get around to looking at how to acquire push permission for ELPA.

**Comment by phillord** [comment] 2016-01-21 19:43
Create an account on savannah, add keys, mail emacs-devel would probably do the trick.

You need to do a release also. Commits to ELPA only appear when there is a version update.

**Comment by capitaomorte** [comment] 2016-01-21 22:40
I just did the merge

```
commit 5817fe1ff1059fd505dc5e6d5171f545866bee91
Merge: da68117 1a98c38
Author: João Távora <joaotavora@gmail.com>
Date:   Thu Jan 21 22:29:10 2016 +0000

    Update packages/yasnippet by subtree-merging from its external upstream
    
    Again, packages/yasnippet/snippets is left untouched in GNU ELPA. The
    upstream version uses a submodule pointing to a snippets repo which
    lives at https://github.com/AndreaCrotti/yasnippet-snippets.git
    
    Conflicts: packages/yasnippet/snippets
```

For reference, I used

```
git subtree pull --prefix=packages/yasnippet yasnippet master
``` 

In the ELPA.git repo root. This makes a conflict for `/packages/yasnippet/snippets` which is solved by resolving to ELPA.git's version using, for example:

```
git checkout master -- packages/yasnippet/snippets  
```

Regarding the release, @npostavs I know it's silly, but can you point me to the issue where we discussed this some time ago and remind me again what I have to do (I think it was updating a NEWS file with some info from a bunch of ancient commits).

**Comment by npostavs** [comment] 2016-01-22 05:03
It was #512. The NEWS file is in the news branch, but I haven't added more recent changes yet, i.e. none of https://github.com/capitaomorte/yasnippet/compare/news...master are mentioned.

The plan was that you were going to add more details about earlier changes, circa 0.8 to 0.9. 

If you don't have the time for that, I think it's not a great tragedy to make a release with a bit less detail about old bug fixes.

**Comment by npostavs** [comment] 2016-01-22 15:42
How come the docs are under `doc/doc/` in ELPA? Seems to have happened in the last merge, but this recent merge successfully update the documents anyway??

```
39a27b6cd6ced60e81145efb18d72d6081eac9f7
Author:     JoÃ£o TÃ¡vora <joaotavora@gmail.com>
AuthorDate: Sat Mar 28 15:16:36 2015 +0000
Commit:     JoÃ£o TÃ¡vora <joaotavora@gmail.com>
CommitDate: Sat Mar 28 15:39:29 2015 +0000

Parent:     73701d9 Update packages/darkroom by merging its external subtree
Parent:     a467019 `yas-minor-mode' assertion broke a test. Good. Fix it.
Containing: master

Update packages/yasnippet by merging from its external upstream subtree

The snippet collection and the "yasmate" tool, realized in the
upstream as git submodules, are removed in the merge result. The "old"
snippet collection is however still in place in
packages/yasnippet/snippets.
...
31 files changed, 2263 insertions(+), 64187 deletions(-)
packages/yasnippet/.gitmodules                     |    16 +-
packages/yasnippet/.travis.yml                     |    24 +
packages/yasnippet/CONTRIBUTING.md                 |    27 +
packages/yasnippet/README.mdown                    |   147 +-
packages/yasnippet/Rakefile                        |    54 +-
packages/yasnippet/doc/doc/.nosearch               |     0 
packages/yasnippet/doc/doc/faq.org                 |   158 +
packages/yasnippet/doc/doc/index.org               |    47 +
packages/yasnippet/doc/doc/nav-menu.html.inc       |    16 +
packages/yasnippet/doc/doc/org-setup.inc           |    11 +
packages/yasnippet/doc/doc/snippet-development.org |   424 +
packages/yasnippet/doc/doc/snippet-expansion.org   |   262 +
packages/yasnippet/doc/doc/snippet-menu.org        |    69 +
.../yasnippet/doc/doc/snippet-organization.org     |   121 +
packages/yasnippet/doc/doc/snippet-reference.org   |    12 +
packages/yasnippet/doc/doc/stylesheets/manual.css  |    26 +
packages/yasnippet/doc/manual.mdown                |   257 -
packages/yasnippet/doc/yas-doc-helper.el           |   130 +-
...
```

**Comment by capitaomorte** [comment] 2016-01-23 15:54
Hmmm, seems like a merge blunder caused by mergin the old markdown version with the new org version. I'll fix it by hand and keep an eye on it on the next merge.

**Comment by capitaomorte** [comment] 2016-01-23 16:12
I just fixed it, thanks for noticing. Git should understand the `git mv`s that I did just now,  and act accordingly. The only differences now between this `doc` and ELPA.git's `doc` is a lone copyright assignment still in my name, should be changed to FSF as someone already did in ELPA.git

**Comment by phillord** [comment] 2016-01-25 12:39
ELPA still has 0.8 on release.

I notice that the headers look like this.

    ;; Version: 0.8.1
    ;; Package-version: 0.8.0

Is this deliberate? It looks like package-version is taking priority.

Phil

**Comment by capitaomorte** [comment] 2016-01-25 12:41
@phillord, I don't know anymore, probably not. But thanks for pointing out that detail. I'll try to do my part of the release process asap.

**Comment by npostavs** [comment] 2016-04-03 17:03
I've pushed `0.9.1` to GNU ELPA, not sure how fast the server updates, I guess it should be available by tomorrow.

**Comment by npostavs** [comment] 2016-04-04 17:32
New version is available GNU ELPA now.

**Closed by npostavs** 2016-04-04 17:32 UTC
